version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ats-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ats_db
      MYSQL_USER: ats_user
      MYSQL_PASSWORD: ats_password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
